export const APP_ROUTES = {
    START: "start",
    LOGIN: "login",
    INITIAL_CHOICE: "init",
    REGISTER: "register",
    MAIN: "main",
    HOME: "home",
    SEARCH: "search",
    EVENTS: "events",
    EVENT_DETAILS: "event-details",
    MAP: "map",
    PROFILE: "profile",
    PROFILE_EDIT: "edit",
    RECIPES: "recipes",
    RECIPE_DETAILS: "recipe-details",
    RECOVER_PASSWORD: "recover",
}