export const ESTADOS = [
    {"EST_NOME": "Acre", "EST_SIGLA": "AC"},
    {"EST_NOME": "Alagoas", "EST_SIGLA": "AL"},
    {"EST_NOME": "Amapá", "EST_SIGLA": "AP"},
    {"EST_NOME": "Amazonas", "EST_SIGLA": "AM"},
    {"EST_NOME": "Bahia", "EST_SIGLA": "BA"},
    {"EST_NOME": "Ceará", "EST_SIGLA": "CE"},
    {"EST_NOME": "Distrito Federal", "EST_SIGLA": "DF"},
    {"EST_NOME": "Espírito Santo", "EST_SIGLA": "ES"},
    {"EST_NOME": "Goiás", "EST_SIGLA": "GO"},
    {"EST_NOME": "Maranhão", "EST_SIGLA": "MA"},
    {"EST_NOME": "Mato Grosso", "EST_SIGLA": "MT"},
    {"EST_NOME": "Mato Grosso do Sul", "EST_SIGLA": "MS"},
    {"EST_NOME": "Minas Gerais", "EST_SIGLA": "MG"},
    {"EST_NOME": "Pará", "EST_SIGLA": "PA"},
    {"EST_NOME": "Paraíba", "EST_SIGLA": "PB"},
    {"EST_NOME": "Paraná", "EST_SIGLA": "PR"},
    {"EST_NOME": "Pernambuco", "EST_SIGLA": "PE"},
    {"EST_NOME": "Piauí", "EST_SIGLA": "PI"},
    {"EST_NOME": "Rio de Janeiro", "EST_SIGLA": "RJ"},
    {"EST_NOME": "Rio Grande do Norte", "EST_SIGLA": "RN"},
    {"EST_NOME": "Rio Grande do Sul", "EST_SIGLA": "RS"},
    {"EST_NOME": "Rondônia", "EST_SIGLA": "RO"},
    {"EST_NOME": "Roraima", "EST_SIGLA": "RR"},
    {"EST_NOME": "Santa Catarina", "EST_SIGLA": "SC"},
    {"EST_NOME": "São Paulo", "EST_SIGLA": "SP"},
    {"EST_NOME": "Sergipe", "EST_SIGLA": "SE"},
    {"EST_NOME": "Tocantins", "EST_SIGLA": "TO"}

]