import { Organization } from '../models/organization-model';

export const NOTIFICATIONS = [
    {
        id: 5,
        user_id: 1,
        cited_user_id: 1,
        cited_user_image: 'adam.jpg',
        title: 'sua publicaÃ§Ã£o recebeu uma curtida!',
        description: 'gabriel ortiz curtiu sua publicaÃ§Ã£o.',
        date: '2024-05-05T17:15:00Z',
        read: true,
        type: 'like',
    },
    {
        id: 4,
        user_id: 1,
        cited_user_id: 6,
        cited_user_image: 'larry.png',
        title: 'vocÃª foi mencionado!',
        description: 'lauro santos mencionou vocÃª em uma publicaÃ§Ã£o.',
        date: '2024-03-10T09:45:00Z',
        read: true,
        type: 'mention',
    },
    {
        id: 2,
        user_id: 1,
        cited_user_id: 3,
        cited_user_image: 'maria.png',
        title: 'novo seguidor!',
        description: 'maria fuller comeÃ§ou a seguir vocÃª.',
        date: '2024-01-15T10:30:00Z',
        read: false,
        type: 'follower',
    },
    {
        id: 3,
        user_id: 1,
        cited_user_id: 10,
        cited_user_image: 'mike.png',
        title: 'novo comentÃ¡rio na sua publicaÃ§Ã£o!',
        description: 'rogÃ©rio alvarez comentou na sua publicaÃ§Ã£o.',
        date: '2022-12-20T14:20:00Z',
        read: true,
        type: 'comment',
    },
    {
        id: 6,
        user_id: 1,
        cited_user_id: 5,
        cited_user_image: 'laura.png',
        title: 'convite para evento!',
        description: 'laura sara te convidou para o vegan festival.',
        date: '2025-09-12T11:00:00Z',
        read: false,
        type: 'mention',
    },
];

export const POSTS = [
    {
        post_id: 20001,
        creator_id: 4,
        creator: 'Lucas Almeida',
        creator_image: 'russell.png',
        registerDate: '2026-09-22T09:15:00',
        image: 'slider-default.jpeg',
        text: 'café da manhã plant-based: panqueca de banana, pasta de amendoim e muita energia pra começar o dia.',
        liked: false,
        saved: false,
        reposts: 3,
        likes: [{ user_id: 1 }, { user_id: 3 }, { user_id: 6 }],
        comments: [{ user_id: 1, comment: 'quero a receita!' }, { user_id: 6, comment: 'ficou lindo' }],
    },
    {
        post_id: 20002,
        creator_id: 1,
        creator: 'Gabriel Ortiz',
        creator_image: 'adam.jpg',
        registerDate: '2026-09-22T07:40:00',
        image: null,
        text: 'alguém indica um restaurante vegano bom perto da paulista? aceito dicas de almoço rápido.',
        liked: true,
        saved: false,
        reposts: 1,
        likes: [{ user_id: 2 }, { user_id: 4 }, { user_id: 5 }],
        comments: [{ user_id: 4, comment: 'tem um ótimo na consolação!' }],
    },
    {
        post_id: 20003,
        creator_id: 3,
        creator: 'Maria Fuller',
        creator_image: 'maria.png',
        registerDate: '2026-09-21T18:20:00',
        image: 'recipe01.jpg',
        text: 'testei panqueca de abacate hoje e ficou incrível. postei a receita completa na aba de receitas.',
        liked: false,
        saved: true,
        reposts: 8,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 4 }, { user_id: 5 }, { user_id: 6 }],
        comments: [{ user_id: 5, comment: 'vou fazer amanhã' }, { user_id: 2, comment: 'amei a foto' }],
    },
    {
        post_id: 20004,
        creator_id: 6,
        creator: 'Lauro Santos',
        creator_image: 'larry.png',
        registerDate: '2026-09-20T14:10:00',
        image: 'event01.jpg',
        text: 'fui no vegan festival e voltei cheio de ideias. a feira de produtos locais estava demais.',
        liked: false,
        saved: false,
        reposts: 12,
        likes: [{ user_id: 1 }, { user_id: 3 }, { user_id: 4 }, { user_id: 10 }],
        comments: [{ user_id: 10, comment: 'também estava lá!' }],
    },
    {
        post_id: 20005,
        creator_id: 5,
        creator: 'Laura Sara',
        creator_image: 'laura.png',
        registerDate: '2026-09-18T11:00:00',
        image: null,
        text: 'lembrete: substituir leite animal por leite de aveia no café muda tudo. transição sem sofrimento.',
        liked: false,
        saved: false,
        reposts: 5,
        likes: [{ user_id: 3 }, { user_id: 4 }],
        comments: [{ user_id: 3, comment: 'concordo demais' }],
    },
    {
        post_id: 20006,
        creator_id: 10,
        creator: 'Rogério Alvarez',
        creator_image: 'mike.png',
        registerDate: '2026-09-10T16:45:00',
        image: 'recipe02.jpg',
        text: 'yakisoba vegetariano caseiro no ponto. o segredo é o molho e não exagerar no fogo.',
        liked: false,
        saved: false,
        reposts: 4,
        likes: [{ user_id: 1 }, { user_id: 6 }, { user_id: 7 }],
        comments: [{ user_id: 1, comment: 'manda o passo a passo' }],
    },
    {
        post_id: 20007,
        creator_id: 4,
        creator: 'Lucas Almeida',
        creator_image: 'russell.png',
        registerDate: '2026-08-28T20:00:00',
        image: 'event05.jpg',
        text: 'organizei um brunch com o russell vegan club. próxima edição em outubro — quem vem?',
        liked: false,
        saved: false,
        reposts: 9,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 5 }, { user_id: 6 }],
        comments: [{ user_id: 5, comment: 'eu vou!' }, { user_id: 2, comment: 'conta comigo' }],
    },
    {
        post_id: 20008,
        creator_id: 2,
        creator: 'Alberto Willians',
        creator_image: 'default-user.png',
        registerDate: '2026-07-15T09:30:00',
        image: null,
        text: 'comecei a transição vegetariana há 30 dias. dica: planejar o cardápio da semana ajuda muito.',
        liked: false,
        saved: false,
        reposts: 2,
        likes: [{ user_id: 4 }, { user_id: 8 }],
        comments: [{ user_id: 4, comment: 'parabéns pela jornada' }],
    },
    {
        post_id: 20009,
        creator_id: 5,
        creator: 'Laura Sara',
        creator_image: 'laura.png',
        registerDate: '2026-05-02T12:00:00',
        image: 'recipe03.jpg',
        text: 'meu cantinho verde cresceu. hortinha de manjericão, alecrim e tomate-cereja na varanda.',
        liked: false,
        saved: false,
        reposts: 6,
        likes: [{ user_id: 1 }, { user_id: 3 }, { user_id: 4 }, { user_id: 6 }],
        comments: [{ user_id: 6, comment: 'inspirador' }],
    },
    {
        post_id: 20010,
        creator_id: 1,
        creator: 'Gabriel Ortiz',
        creator_image: 'adam.jpg',
        registerDate: '10/03/2022',
        image: 'slider-default.jpeg',
        text: 'primeira feira vegana que fui. até hoje lembro do cheiro de comida boa e das conversas.',
        liked: false,
        saved: false,
        reposts: 15,
        likes: [{ user_id: 2 }, { user_id: 3 }, { user_id: 4 }, { user_id: 5 }],
        comments: [{ user_id: 3, comment: 'saudades dessa época' }],
    },
    {
        post_id: 20011,
        creator_id: 4,
        creator: 'Lucas Almeida',
        creator_image: 'russell.png',
        registerDate: '2026-09-22T11:05:00',
        image: null,
        text: 'código + café de aveia. se alguém tiver podcast bom sobre veganismo e tech, recomenda aí.',
        liked: false,
        saved: false,
        reposts: 0,
        likes: [{ user_id: 6 }],
        comments: [],
    },
    {
        post_id: 20012,
        creator_id: 3,
        creator: 'Maria Fuller',
        creator_image: 'maria.png',
        registerDate: '2026-09-19T08:00:00',
        image: 'recipe04.jpg',
        text: 'patê de rúcula em 10 minutos. perfeito pro pão de forma integral no lanche da tarde.',
        liked: false,
        saved: false,
        reposts: 7,
        likes: [{ user_id: 1 }, { user_id: 4 }, { user_id: 10 }],
        comments: [{ user_id: 10, comment: 'salvei aqui' }],
    },
];

export const RECIPES = [
    {
        id: 4343,
        creator_id: 1,
        creator: 'FGV',
        creator_image: null,
        registerDate: '10/04/2022',
        images: ['recipe01.jpg', 'recipe01.jpg', 'recipe01.jpg'],
        title: 'Panqueca de Avocado',
        instructions: `
        - PreparaÃ§Ã£o do Avocado: Corte o avocado ao meio, retire o caroÃ§o e, com uma colher, retire a polpa. Amasse a polpa do avocado com um garfo atÃ© formar um purÃª liso.<br>
        - Mistura dos Ingredientes Secos: Em uma tigela grande, misture a farinha, o aÃ§Ãºcar, o fermento em pÃ³, o bicarbonato de sÃ³dio e o sal.<br>
        - Mistura dos Ingredientes Molhados: Em outra tigela, bata o ovo. Adicione o leite, o Ã³leo (ou manteiga derretida), o purÃª de avocado e o extrato de baunilha. Misture bem atÃ© que todos os ingredientes estejam incorporados.<br>
        - CombinaÃ§Ã£o dos Ingredientes: Despeje a mistura dos ingredientes molhados sobre os ingredientes secos. Mexa delicadamente atÃ© que a massa esteja homogÃªnea, mas nÃ£o misture demais. A massa deve ter alguns grumos.<br>
        - Cozimento das Panquecas: AqueÃ§a uma frigideira grande ou uma chapa em fogo mÃ©dio. Unte levemente com manteiga ou Ã³leo. Despeje cerca de 1/4 de xÃ­cara de massa na frigideira para cada panqueca. Cozinhe atÃ© que bolhas comecem a se formar na superfÃ­cie da panqueca e as bordas pareÃ§am firmes, cerca de 2-3 minutos. Vire a panqueca e cozinhe por mais 1-2 minutos atÃ© que esteja dourada dos dois lados. Transfira as panquecas prontas para um prato e mantenha-as aquecidas enquanto cozinha o restante da massa.<br>
        - Servir: Sirva as panquecas de avocado quentes, acompanhadas de mel, xarope de bordo, frutas frescas ou iogurte, conforme desejado.<br>`,
        ingredients: ['1 avocado maduro (ou abacate pequeno)', '1 xÃ­cara de farinha de trigo (ou farinha de trigo integral para uma versÃ£o mais saudÃ¡vel)', '1 colher de sopa de aÃ§Ãºcar (pode ser substituÃ­do por mel ou adoÃ§ante a gosto)', '1 colher de chÃ¡ de fermento em pÃ³', '1/2 colher de chÃ¡ de bicarbonato de sÃ³dio', '1/4 colher de chÃ¡ de sal', '1 ovo grande', '1 xÃ­cara de leite (pode usar leite vegetal como amÃªndoa, soja ou aveia)', '1 colher de sopa de Ã³leo vegetal (ou manteiga derretida)', '1 colher de chÃ¡ de extrato de baunilha', 'Manteiga ou Ã³leo para cozinhar as panquecas'],
        cookTime: '30 min',
        servings: 4,
        calories: 300,
        liked: false,
        favorited: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }],
    },
    {
        id: 211,
        creator_id: 2,
        creator: 'Maria Fuller',
        creator_image: 'maria.png',
        registerDate: '12/04/2022',
        images: ['recipe02.jpg'],
        title: 'Yakisoba Vegetariano',
        instructions: `
        - Cozimento do MacarrÃ£o: Em uma panela grande com Ã¡gua fervente e salgada, cozinhe o macarrÃ£o para yakisoba conforme as instruÃ§Ãµes da embalagem, atÃ© que esteja al dente. Reserve 1 xÃ­cara da Ã¡gua do cozimento, depois escorra o macarrÃ£o.
        - PreparaÃ§Ã£o dos Legumes: Enquanto o macarrÃ£o cozinha, aqueÃ§a um pouco de Ã³leo em uma frigideira grande ou wok em fogo mÃ©dio-alto. Adicione a cenoura, os pimentÃµes, o brÃ³colis, a couve-flor, a cebola e o alho-porÃ³. Refogue por cerca de 5 minutos atÃ© que os legumes estejam macios, mas ainda crocantes.
        - Molho e FinalizaÃ§Ã£o: Em uma tigela pequena, misture o molho de soja, o molho de ostra vegetariano, o saquÃª mirin, o amido de milho e o azeite de gergelim. Despeje o molho sobre os legumes na frigideira e mexa bem para cobrir. Adicione o alho picado e continue cozinhando por mais 1-2 minutos.
        - Mistura com MacarrÃ£o: Adicione o macarrÃ£o cozido Ã  frigideira com os legumes e o molho. Mexa delicadamente para combinar todos os ingredientes e aquecer o macarrÃ£o. Se o molho parecer muito grosso, adicione um pouco da Ã¡gua do cozimento reservada atÃ© atingir a consistÃªncia desejada.
        - Servir: Divida o yakisoba vegetariano em pratos individuais e sirva imediatamente. VocÃª pode polvilhar com cebolinha picada ou sementes de gergelim torradas para decorar, se desejar.`,
        ingredients: [
            "300g de macarrÃ£o para yakisoba", "1 unidade grande de cenoura",
            "1 unidade de pimentÃ£o vermelho", "1 unidade de pimentÃ£o amarelo",
            "1 maÃ§o de brÃ³colis", "1/2 cabeÃ§a de couve-flor",
            "1 unidade grande de cebola", "1 unidade mÃ©dia de alho-porÃ³",
            "1/4 xÃ­cara de molho de soja", "2 colheres de sopa de molho de ostra vegetariano",
            "2 colheres de sopa de saquÃª mirin", "1 colher de sopa de amido de milho",
            "1 colher de chÃ¡ de azeite de gergelim", "2 dentes de alho picado"
        ],
        cookTime: '25 min',
        servings: 6,
        calories: 350,
        liked: false,
        favorited: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }, { user_id: 4, comment: 'dddddd' }, { user_id: 5, comment: 'eeeee' }],
    },
    {
        id: 232,
        creator_id: 3,
        creator: 'Tomás Neto',
        creator_image: null,
        registerDate: '23/05/2022',
        images: ['recipe03.jpg'],
        title: 'Farofa VerÃ£o',
        instructions: `
    - Preparo dos Ingredientes: AqueÃ§a uma frigideira grande em fogo mÃ©dio. Adicione o azeite e refogue a cebola e o alho atÃ© ficarem macios e perfumados, cerca de 3 minutos.
    - AdiÃ§Ã£o dos Legumes: Acrescente a cenoura, o pimentÃ£o, o milho, a ervilha e os pimentÃµes Ã  frigideira. Cozinhe por mais 5 minutos, mexendo ocasionalmente, atÃ© que os legumes estejam macios.
    - Farofa: Adicione a farinha de mandioca Ã  frigideira e mexa bem para incorporar todos os ingredientes. Cozinhe por mais 3-5 minutos, mexendo sempre, atÃ© que a farofa esteja dourada e crocante.
    - FinalizaÃ§Ã£o e Servir: Tempere a farofa com sal e pimenta a gosto. Transfira para uma travessa de servir e polvilhe com salsinha picada antes de servir.`,
        ingredients: [
            "2 xÃ­caras de farinha de mandioca",
            "1 colher de sopa de azeite de oliva",
            "1 cebola mÃ©dia picada",
            "2 dentes de alho picados",
            "1 cenoura ralada",
            "1/2 pimentÃ£o vermelho picado",
            "1/2 pimentÃ£o amarelo picado",
            "1/2 xÃ­cara de milho verde",
            "1/2 xÃ­cara de ervilha",
        ],
        cookTime: '20 min',
        servings: 6,
        calories: 250,
        liked: false,
        favorited: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }],
    },
    {
        id: 543,
        creator_id: 4,
        creator: 'Lucas Almeida',
        creator_image: 'russell.png',
        registerDate: '28/05/2022',
        images: ['recipe04.jpg'],
        title: 'PatÃª de RÃºcula',
        instructions: 'Add the cooked spaghetti to the skillet with the pancetta and garlic. Toss to combine. Remove the skillet from heat and quickly stir in the egg and cheese mixture, using tongs to evenly coat the spaghetti. If the sauce seems too thick, add reserved pasta water, a little at a time, until desired consistency is reached. Season with freshly ground black pepper and salt to taste. Garnish with chopped fresh parsley before serving. Enjoy your delicious Spaghetti Carbonara!',
        ingredients: [
            "2 xÃ­caras de folhas de rÃºcula",
            "1 xÃ­cara de castanha de caju crua",
            "1/4 de xÃ­cara de azeite de oliva",
            "Suco de 1 limÃ£o",
            "2 dentes de alho",
            "Sal e pimenta-do-reino a gosto"
        ],
        cookTime: '30 min',
        servings: 4,
        calories: 300,
        liked: false,
        favorited: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }],
    },
    {
        id: 601,
        creator_id: 4,
        creator: 'Lucas Almeida',
        creator_image: 'russell.png',
        registerDate: '12/09/2026',
        images: ['recipe01.jpg'],
        title: 'smoothie verde energizante',
        instructions: 'bata banana, espinafre, leite de aveia e pasta de amendoim até ficar cremoso. sirva gelado.',
        ingredients: [
            '1 banana congelada',
            '1 xícara de espinafre',
            '200 ml de leite de aveia',
            '1 colher de sopa de pasta de amendoim',
        ],
        cookTime: '5 min',
        servings: 1,
        calories: 220,
        liked: false,
        favorited: false,
        likes: [{ user_id: 1 }, { user_id: 5 }],
        comments: [{ user_id: 5, comment: 'perfeito pós-treino' }],
    },
    {
        id: 602,
        creator_id: 5,
        creator: 'Laura Sara',
        creator_image: 'laura.png',
        registerDate: '05/09/2026',
        images: ['recipe02.jpg'],
        title: 'bolo de cenoura sem ovo',
        instructions: 'misture os secos, acrescente óleo, leite vegetal e cenoura ralada. asse a 180°C por 40 minutos.',
        ingredients: [
            '2 xícaras de farinha de trigo',
            '1 xícara de açúcar demerara',
            '1 xícara de cenoura ralada',
            '1/2 xícara de óleo',
            '1 xícara de leite de amêndoas',
            '1 colher de sopa de fermento',
        ],
        cookTime: '50 min',
        servings: 8,
        calories: 280,
        liked: false,
        favorited: false,
        likes: [{ user_id: 3 }, { user_id: 4 }, { user_id: 6 }],
        comments: [{ user_id: 4, comment: 'cobertura de chocolate?' }],
    },
    {
        id: 603,
        creator_id: 6,
        creator: 'Lauro Santos',
        creator_image: 'larry.png',
        registerDate: '01/09/2026',
        images: ['recipe03.jpg'],
        title: 'hummus clássico',
        instructions: 'processe grão-de-bico, tahine, limão, alho e azeite. ajuste o sal e sirva com páprica.',
        ingredients: [
            '1 lata de grão-de-bico',
            '2 colheres de sopa de tahine',
            'suco de 1 limão',
            '1 dente de alho',
            'azeite a gosto',
        ],
        cookTime: '15 min',
        servings: 4,
        calories: 180,
        liked: false,
        favorited: false,
        likes: [{ user_id: 1 }, { user_id: 2 }],
        comments: [{ user_id: 1, comment: 'com torrada fica top' }],
    },
    {
        id: 604,
        creator_id: 4,
        creator: 'Lucas Almeida',
        creator_image: 'russell.png',
        registerDate: '20/08/2026',
        images: ['recipe04.jpg'],
        title: 'wrap de grão-de-bico',
        instructions: 'amasse o grão-de-bico temperado, monte no wrap com salada e molho de tahine.',
        ingredients: [
            '1 wrap integral',
            '1 xícara de grão-de-bico cozido',
            'alface e tomate',
            '2 colheres de tahine diluído',
        ],
        cookTime: '15 min',
        servings: 2,
        calories: 320,
        liked: false,
        favorited: false,
        likes: [{ user_id: 3 }, { user_id: 10 }],
        comments: [{ user_id: 10, comment: 'almoço fácil' }],
    },
    {
        id: 605,
        creator_id: 1,
        creator: 'Gabriel Ortiz',
        creator_image: 'adam.jpg',
        registerDate: '18/09/2026',
        images: ['recipe01.jpg'],
        title: 'guacamole rápido',
        instructions: 'amasse o abacate com limão e sal. acrescente tomate, cebola e coentro. sirva com chips ou torradas.',
        ingredients: [
            '2 abacates maduros',
            'suco de 1 limão',
            '1 tomate picado',
            '1/4 de cebola roxa',
            'coentro a gosto',
            'sal a gosto',
        ],
        cookTime: '10 min',
        servings: 3,
        calories: 190,
        liked: false,
        favorited: false,
        likes: [{ user_id: 3 }, { user_id: 4 }],
        comments: [{ user_id: 4, comment: 'petisco perfeito' }],
    },
    {
        id: 606,
        creator_id: 3,
        creator: 'Maria Fuller',
        creator_image: 'maria.png',
        registerDate: '14/09/2026',
        images: ['recipe02.jpg'],
        title: 'sopa cremosa de abóbora',
        instructions: 'refogue alho e cebola. cozinhe a abóbora até amolecer. bata no liquidificador com leite vegetal e tempere.',
        ingredients: [
            '500g de abóbora',
            '1 cebola',
            '2 dentes de alho',
            '400 ml de leite de coco',
            'azeite, sal e pimenta',
        ],
        cookTime: '35 min',
        servings: 4,
        calories: 210,
        liked: false,
        favorited: false,
        likes: [{ user_id: 1 }, { user_id: 5 }, { user_id: 6 }],
        comments: [{ user_id: 5, comment: 'conforto em forma de sopa' }],
    },
    {
        id: 607,
        creator_id: 5,
        creator: 'Laura Sara',
        creator_image: 'laura.png',
        registerDate: '10/09/2026',
        images: ['recipe03.jpg'],
        title: 'granola caseira',
        instructions: 'misture aveia, castanhas, óleo de coco e melado. asse a 160°C por 25 minutos mexendo na metade.',
        ingredients: [
            '2 xícaras de aveia em flocos',
            '1/2 xícara de castanhas picadas',
            '3 colheres de sopa de óleo de coco',
            '3 colheres de sopa de melado',
            'canela a gosto',
        ],
        cookTime: '30 min',
        servings: 8,
        calories: 160,
        liked: false,
        favorited: false,
        likes: [{ user_id: 2 }, { user_id: 4 }],
        comments: [{ user_id: 2, comment: 'fica crocante demais' }],
    },
    {
        id: 608,
        creator_id: 4,
        creator: 'Lucas Almeida',
        creator_image: 'russell.png',
        registerDate: '08/09/2026',
        images: ['recipe04.jpg'],
        title: 'tofu grelhado com ervas',
        instructions: 'presse o tofu, marine com azeite, alho e ervas. grelhe 4 minutos de cada lado até dourar.',
        ingredients: [
            '1 bloco de tofu firme',
            '2 colheres de sopa de azeite',
            '2 dentes de alho',
            'alecrim e tomilho',
            'sal e pimenta',
        ],
        cookTime: '20 min',
        servings: 2,
        calories: 240,
        liked: false,
        favorited: false,
        likes: [{ user_id: 1 }, { user_id: 3 }, { user_id: 10 }],
        comments: [{ user_id: 1, comment: 'proteína no ponto' }],
    },
];

export const ORGANIZATIONS: Organization[] = [
    {
        id: 1,
        name: 'fgv veg',
        description: 'coletivo de estudantes e professores pela alimentaÃ§Ã£o consciente.',
        image: '',
        owner_id: 1,
        city: 'sÃ£o paulo',
        created_at: '01/03/2022',
        members: [
            { user_id: 1, role: 'owner' },
            { user_id: 2, role: 'member' },
            { user_id: 5, role: 'member' },
        ],
    },
    {
        id: 2,
        name: 'irani green',
        description: 'marca e comunidade focada em feiras e experiÃªncias veganas.',
        image: '',
        owner_id: 3,
        city: 'sÃ£o paulo',
        created_at: '12/01/2022',
        members: [
            { user_id: 3, role: 'owner' },
            { user_id: 6, role: 'admin' },
            { user_id: 10, role: 'member' },
        ],
    },
    {
        id: 3,
        name: 'vokin collective',
        description: 'encontros mÃ­sticos, yoga e alimentaÃ§Ã£o plant-based.',
        image: '',
        owner_id: 5,
        city: 'rio de janeiro',
        created_at: '20/05/2022',
        members: [
            { user_id: 5, role: 'owner' },
            { user_id: 7, role: 'member' },
            { user_id: 8, role: 'member' },
        ],
    },
    {
        id: 4,
        name: 'russell vegan club',
        description: 'comunidade do russell para organizar encontros e feiras veganas.',
        image: '',
        owner_id: 4,
        city: 'sÃ£o paulo',
        created_at: '01/09/2026',
        members: [
            { user_id: 4, role: 'owner' },
        ],
    },
];

export const EVENTS = [
    {
        id: 101,
        organization_id: 1,
        creator_id: 1,
        creator: 'fgv veg',
        creator_image: '',
        registerDate: '09/10/2022',
        image: 'event01.jpg',
        title: 'vegan festival',
        category: 'festival',
        local: 'parque ibirapuera, sÃ£o paulo',
        startingDate: '10/10/2026',
        endingDate: '12/10/2026',
        startingHour: '10:00',
        endingHour: '18:00',
        description: 'um evento anual que celebra o estilo de vida vegano com uma variedade de palestras, workshops de culinÃ¡ria e estandes de produtos veganos. Ã© uma Ã³tima oportunidade para aprender mais sobre alimentaÃ§Ã£o sustentÃ¡vel e saudÃ¡vel.',
        confirmed: [1, 2, 3, 5, 6, 10],
        comments: [{ user_id: 1, comment: 'quero ir!' }, { user_id: 2, comment: 'vai ser incrÃ­vel' }],
    },
    {
        id: 102,
        organization_id: 2,
        creator_id: 3,
        creator: 'irani green',
        creator_image: null,
        registerDate: '05/04/2022',
        image: 'event02.jpg',
        title: 'vegan fest',
        category: 'feira',
        local: 'avenida paulista, sÃ£o paulo',
        startingDate: '11/10/2026',
        endingDate: null,
        startingHour: '10:00',
        endingHour: '18:00',
        description: 'um dos maiores encontros veganos, oferecendo uma vasta gama de alimentos e produtos cruelty-free. inclui demonstraÃ§Ãµes de chefs renomados, atividades interativas e painÃ©is de discussÃ£o sobre temas ambientais e de bem-estar animal.',
        confirmed: [3, 5, 6, 8, 10],
        comments: [{ user_id: 3, comment: 'evento top' }],
    },
    {
        id: 103,
        organization_id: 2,
        creator_id: 3,
        creator: 'irani green',
        creator_image: null,
        registerDate: '10/03/2022',
        image: 'event03.jpg',
        title: 'vegan street market',
        category: 'mercado',
        local: 'rua Augusta, sÃ£o paulo',
        startingDate: '17/10/2026',
        endingDate: null,
        startingHour: '12:00',
        endingHour: '18:00',
        description: 'um mercado de rua vibrante, cheio de barracas que vendem comida vegana fresca, bebidas e produtos artesanais. ideal para descobrir novas delÃ­cias veganas e apoiar pequenos negÃ³cios locais.',
        confirmed: [1, 2, 3, 5, 6, 7, 10],
        comments: [{ user_id: 1, comment: 'amo esse market' }],
    },
    {
        id: 104,
        organization_id: 3,
        creator_id: 5,
        creator: 'vokin collective',
        creator_image: null,
        registerDate: '10/03/2022',
        image: 'event04.jpg',
        title: 'vegan mystic fest',
        category: 'bem-estar',
        local: 'jardim botÃ¢nico, rio de janeiro',
        startingDate: '18/10/2026',
        endingDate: null,
        startingHour: '12:00',
        endingHour: '18:00',
        description: 'um festival que combina espiritualidade e veganismo, com foco em bem-estar holÃ­stico. oferece sessÃµes de meditaÃ§Ã£o, yoga, palestras sobre alimentaÃ§Ã£o consciente e uma variedade de opÃ§Ãµes de alimentaÃ§Ã£o vegana.',
        confirmed: [5, 7, 8],
        comments: [{ user_id: 5, comment: 'namastÃª' }],
    },
    {
        id: 105,
        organization_id: 4,
        creator_id: 4,
        creator: 'russell vegan club',
        creator_image: 'russell.png',
        registerDate: '02/09/2026',
        image: 'event05.jpg',
        title: 'brunch plant-based',
        category: 'encontro',
        local: 'vila madalena, sÃ£o paulo',
        startingDate: '25/10/2026',
        endingDate: null,
        startingHour: '09:30',
        endingHour: '12:30',
        description: 'um brunch descontraÃ­do para experimentar receitas plant-based, trocar dicas de alimentaÃ§Ã£o e conhecer gente nova da comunidade vegana.',
        confirmed: [1, 2, 4, 6],
        comments: [{ user_id: 4, comment: 'vem brunchar!' }],
    },
    {
        id: 106,
        organization_id: 1,
        creator_id: 1,
        creator: 'fgv veg',
        creator_image: '',
        registerDate: '15/08/2026',
        image: 'event01.jpg',
        title: 'oficina de culinÃ¡ria vegana',
        category: 'workshop',
        local: 'fgv, avenida 9 de julho, sÃ£o paulo',
        startingDate: '01/11/2026',
        endingDate: null,
        startingHour: '14:00',
        endingHour: '17:00',
        description: 'oficina prÃ¡tica de culinÃ¡ria vegana com foco em pratos do dia a dia, substituiÃ§Ãµes inteligentes e aproveitamento integral dos alimentos.',
        confirmed: [1, 2, 5, 7, 8],
        comments: [{ user_id: 2, comment: 'jÃ¡ anotei na agenda' }],
    },
    {
        id: 107,
        organization_id: 2,
        creator_id: 3,
        creator: 'irani green',
        creator_image: null,
        registerDate: '20/08/2026',
        image: 'event02.jpg',
        title: 'corrida verde 5k',
        category: 'esporte',
        local: 'parque villa-lobos, sÃ£o paulo',
        startingDate: '08/11/2026',
        endingDate: null,
        startingHour: '07:00',
        endingHour: '10:00',
        description: 'corrida e caminhada de 5 km para celebrar movimento, saÃºde e sustentabilidade. kit com lanche plant-based incluso.',
        confirmed: [3, 4, 6, 10],
        comments: [{ user_id: 6, comment: 'bora correr!' }],
    },
    {
        id: 108,
        organization_id: 3,
        creator_id: 5,
        creator: 'vokin collective',
        creator_image: null,
        registerDate: '01/09/2026',
        image: 'event03.jpg',
        title: 'cÃ­rculo de yoga ao ar livre',
        category: 'bem-estar',
        local: 'parque lage, rio de janeiro',
        startingDate: '15/11/2026',
        endingDate: null,
        startingHour: '08:00',
        endingHour: '09:30',
        description: 'prÃ¡tica de yoga suave em meio Ã  natureza, seguida de conversa sobre mindfulness e alimentaÃ§Ã£o consciente.',
        confirmed: [5, 7, 8, 2],
        comments: [{ user_id: 7, comment: 'energia boa' }],
    },
    {
        id: 109,
        organization_id: 4,
        creator_id: 4,
        creator: 'russell vegan club',
        creator_image: 'russell.png',
        registerDate: '10/09/2026',
        image: 'default-events.png',
        title: 'noite de cinema veggie',
        category: 'cultura',
        local: 'cine art, centro, sÃ£o paulo',
        startingDate: '22/11/2026',
        endingDate: null,
        startingHour: '19:00',
        endingHour: '22:00',
        description: 'exibiÃ§Ã£o de documentÃ¡rio sobre veganismo seguida de debate aberto e petiscos plant-based no foyer.',
        confirmed: [1, 4, 5, 8, 10],
        comments: [{ user_id: 1, comment: 'leve pipoca vegana!' }],
    },
    {
        id: 110,
        organization_id: 1,
        creator_id: 1,
        creator: 'fgv veg',
        creator_image: '',
        registerDate: '12/09/2026',
        image: 'event04.jpg',
        title: 'feira de trocas sustentÃ¡veis',
        category: 'feira',
        local: 'praÃ§a da liberdade, belo horizonte',
        startingDate: '29/11/2026',
        endingDate: '30/11/2026',
        startingHour: '10:00',
        endingHour: '17:00',
        description: 'feira colaborativa para trocar livros, roupas e utensÃ­lios, com estandes de produtos locais e alimentos veganos.',
        confirmed: [1, 2, 3, 5],
        comments: [{ user_id: 5, comment: 'vou levar livros' }],
    },
    {
        id: 111,
        organization_id: 2,
        creator_id: 3,
        creator: 'irani green',
        creator_image: null,
        registerDate: '18/09/2026',
        image: 'event05.jpg',
        title: 'hackathon foodtech veg',
        category: 'tecnologia',
        local: 'cubo itau, vila olÃ­mpia, sÃ£o paulo',
        startingDate: '05/12/2026',
        endingDate: '06/12/2026',
        startingHour: '09:00',
        endingHour: '18:00',
        description: 'maratonas de ideias para soluÃ§Ãµes digitais em alimentaÃ§Ã£o plant-based, logÃ­stica sustentÃ¡vel e educaÃ§Ã£o nutricional.',
        confirmed: [3, 4, 6, 7, 10],
        comments: [{ user_id: 3, comment: 'traga notebook' }],
    },
    {
        id: 112,
        organization_id: 4,
        creator_id: 4,
        creator: 'russell vegan club',
        creator_image: 'russell.png',
        registerDate: '20/09/2026',
        image: 'slider-default.jpeg',
        title: 'piquenique no parque',
        category: 'encontro',
        local: 'parque do povo, sÃ£o paulo',
        startingDate: '13/12/2026',
        endingDate: null,
        startingHour: '11:00',
        endingHour: '15:00',
        description: 'piquenique coletivo: cada pessoa leva um prato vegano para compartilhar. jogos, mÃºsica e muita conversa ao ar livre.',
        confirmed: [2, 4, 6, 8],
        comments: [{ user_id: 4, comment: 'traga um prato pra dividir' }],
    },
];

//verificar se não é melhor deixar posts e receitas em uma biblioteca separada
export const USER = {
    id: 4,
    name: 'Lucas Almeida',
    username: 'lucas.almeida',
    description: 'sou programador e vegetariano',
    birth: '19/07/2000',
    email: 'teste@gmail.com',
    phoneNumber: '(11) 99999-9999',
    identify: 'vegan',
    country: 'Brasil',
    city: 'São Paulo',
    state: 'São Paulo',
    background: '',
    image: 'russell.png',
    organization_ids: [4] as number[],
    interests: [
        {
            icon: 'wine-outline',
            color: 'warning',
            description: 'vida noturna',
        },
        {
            icon: 'restaurant-outline',
            color: 'secondary',
            description: 'restaurantes',
        },
        {
            icon: 'videocam-outline',
            color: 'dark',
            description: 'filmes',
        }],
    posts: [] as any[],
    recipes: [
        {
            id: 543,
            creator_id: 4,
            creator: 'Lucas Almeida',
            creator_image: 'russell.png',
            registerDate: '28/05/2022',
            images: ['recipe04.jpg'],
            title: 'patê de rúcula',
            instructions: 'processe rúcula, castanha, azeite, limão e alho até ficar cremoso. ajuste sal e pimenta.',
            ingredients: [
                '2 xícaras de folhas de rúcula',
                '1 xícara de castanha de caju crua',
                '1/4 de xícara de azeite de oliva',
                'suco de 1 limão',
                '2 dentes de alho',
                'sal e pimenta a gosto',
            ],
            cookTime: '30 min',
            servings: 4,
            calories: 300,
            liked: false,
            favorited: false,
            likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
            comments: [{ user_id: 1, comment: 'ficou ótimo no pão' }],
        },
        {
            id: 601,
            creator_id: 4,
            creator: 'Lucas Almeida',
            creator_image: 'russell.png',
            registerDate: '12/09/2026',
            images: ['recipe01.jpg'],
            title: 'smoothie verde energizante',
            instructions: 'bata banana, espinafre, leite de aveia e pasta de amendoim até ficar cremoso.',
            ingredients: [
                '1 banana congelada',
                '1 xícara de espinafre',
                '200 ml de leite de aveia',
                '1 colher de sopa de pasta de amendoim',
            ],
            cookTime: '5 min',
            servings: 1,
            calories: 220,
            liked: false,
            favorited: false,
            likes: [{ user_id: 1 }, { user_id: 5 }],
            comments: [{ user_id: 5, comment: 'perfeito pós-treino' }],
        },
        {
            id: 604,
            creator_id: 4,
            creator: 'Lucas Almeida',
            creator_image: 'russell.png',
            registerDate: '20/08/2026',
            images: ['recipe04.jpg'],
            title: 'wrap de grão-de-bico',
            instructions: 'amasse o grão-de-bico temperado e monte no wrap com salada e tahine.',
            ingredients: [
                '1 wrap integral',
                '1 xícara de grão-de-bico cozido',
                'alface e tomate',
                '2 colheres de tahine diluído',
            ],
            cookTime: '15 min',
            servings: 2,
            calories: 320,
            liked: false,
            favorited: false,
            likes: [{ user_id: 3 }, { user_id: 10 }],
            comments: [{ user_id: 10, comment: 'almoço fácil' }],
        },
    ],
}

export const USERS = [
    { id: 1, name: "Gabriel Ortiz", username: 'gabriel.ortiz', identify: "vegan", image: "adam.jpg", email: "gortiz0@mapy.cz", country: "Brasil", modified: "2015-05-16", birth_date: "1997-05-16" },
    { id: 2, name: "Alberto Willians", username: 'alberto03', identify: "interested", image: "default-user.png", email: "awilliamson1@narod.ru", country: "Brasil", modified: "2015-03-11", birth_date: "1997-03-11" },
    { id: 3, name: "Maria Fuller", username: 'maria.fuller', identify: "vegan", image: "maria.png", email: "mfuller2@npr.org", country: "Brasil", modified: "2015-02-15", birth_date: "1997-02-15" },
    { id: 4, name: "Lucas Almeida", username: 'lucas.almeida', identify: "vegetarian", image: "russell.png", email: "rrobinson3@google.pl", country: "Brasil", modified: "2014-10-31", birth_date: "1997-10-31" },
    { id: 5, name: "Laura Sara", username: 'laura.sara', identify: "vegan", image: "laura.png", email: "lharper4@boston.com", country: "Brasil", modified: "2015-01-14", birth_date: "1997-01-14" },
    { id: 6, name: "Lauro Santos", username: 'lauro.santos', identify: "vegan", image: "larry.png", email: "lsanders5@cornell.edu", country: "Brasil", modified: "2015-01-11", birth_date: "1997-01-11" },
    { id: 7, name: "Miguel Reis", username: 'miguel.reis', identify: "vegan", image: "default-user.png", email: "mrice6@geocities.jp", country: "Brasil", modified: "2014-12-06", birth_date: "1997-12-06" },
    { id: 8, name: "Sara Arias", username: 'sara.arias', identify: "vegetarian", image: "default-user.png", email: "sharris7@deliciousdays.com", country: "Brasil", modified: "2014-11-05", birth_date: "1997-11-05" },
    { id: 9, name: "Filipa Vieira", username: 'filipa.vieira', identify: "vegetarian", image: "default-user.png", email: "pwebb8@reddit.com", country: "Brasil", modified: "2015-04-02", birth_date: "1997-04-02" },
    { id: 10, name: "Rogério Alvarez", username: 'rogerio.alv', identify: "vegan", image: "mike.png", email: "ralvarez9@nsw.gov.au", country: "Brasil", modified: "2015-03-21", birth_date: "1997-03-21" },
    { id: 11, name: "Maria Carpinteiro", username: 'maria.carpinteiro', identify: "interested", image: "default-user.png", email: "mcarpentera@so-net.ne.jp", country: "Brasil", modified: "2015-08-18", birth_date: "1997-08-18" },
];

export const RECENT_SEARCH = [
    { "id": 5, name: "Laura Sara", username: 'laura.sara', identify: "vegan", image: "laura.png", email: "lharper4@boston.com", country: "Brasil", modified: "2015-01-14", birth_date: "1997-01-14" },
    { "id": 6, name: "Lauro Santos", username: 'lauro.santos', identify: "vegan", image: "larry.png", email: "lsanders5@cornell.edu", country: "Brasil", modified: "2015-01-11", birth_date: "1997-01-11" },
    { "id": 11, name: "Maria Carpinteiro", username: 'maria.carpinteiro', identify: "interested", image: "default-user.png", email: "mcarpentera@so-net.ne.jp", country: "Brasil", modified: "2015-08-18", birth_date: "1997-08-18" },
]
