export const NOTIFICATIONS = [
    // {
    //     id: 1,
    //     user_id: 1,
    //     title: 'New message',
    //     description: 'You have a new message from Gary Ortiz',
    //     date: '2023-01-15T10:30:00Z',
    //     read: false,
    //     type: 'message',
    // },
    {
        id: 5,
        user_id: 1,
        cited_user_id: 4,
        title: 'your post got a like!',
        description: 'John Doe liked your post.',
        date: '2024-05-05T17:15:00Z',
        read: true,
        type: 'like',
    },
    {
        id: 4,
        user_id: 1,
        cited_user_id: 4,
        title: 'you were mentioned!',
        description: 'John Doe mentioned you in a post.',
        date: '2024-03-10T09:45:00Z',
        read: true,
        type: 'mention',
    },
    {
        id: 2,
        user_id: 1,
        cited_user_id: 2,
        title: 'new follower alert!',
        description: 'Mary is now following you',
        date: '2024-01-15T10:30:00Z',
        read: false,
        type: 'follower',
    },
    {
        id: 3,
        user_id: 1,
        cited_user_id: 3,
        title: 'someone commented on your post!',
        description: 'Hugo commented on your post',
        date: '2022-12-20T14:20:00Z',
        read: true,
        type: 'comment',
    },
];

export const POSTS = [
    {
        post_id: 13412,
        creator_id: 1,
        creator: 'Gary Ortiz',
        creator_image: 'adam.jpg',
        registerDate: '10/03/2022',
        image: 'slider-default.png',
        text: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }, { user_id: 4 }],
        comments: [{ user_id: 1, comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' }, { user_id: 2, comment: 'Quisque venenatis ante ut erat accumsan mollis.' }, { user_id: 3, comment: 'Phasellus venenatis justo vel elementum sagittis.' }, { user_id: 4, comment: 'Vivamus a nibh ut mauris imperdiet sagittis.' }],
    },
    {
        post_id: 13832,
        creator_id: 6,
        creator: 'Larry',
        creator_image: 'max.png',
        registerDate: null,
        image: null,
        text: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'Sed iaculis urna id elit tincidunt placerat.' }, { user_id: 2, comment: 'Integer at nisi vel odio maximus congue.' }, { user_id: 3, comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' }, { user_id: 4, comment: 'In sit amet urna pellentesque sapien vulputate sodales.' }, { user_id: 5, comment: 'Fusce pretium purus a sapien ultricies pulvinar.' }],
    },
    {
        post_id: 13992,
        creator_id: 3,
        creator: 'Mildred Maria Fuller',
        creator_image: null,
        registerDate: '10/03/2022',
        image: 'slider-default.png',
        text: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }, { user_id: 4 }, { user_id: 5 }],
        comments: [{ user_id: 1, comment: 'Phasellus venenatis justo vel elementum sagittis.' }, { user_id: 2, comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' }, { user_id: 3, comment: 'Nunc quis arcu vitae urna pulvinar viverra ut eget mauris.' }, { user_id: 4, comment: 'Ut id odio quis dui semper varius.' }, { user_id: 5, comment: 'Integer at nisi vel odio maximus congue.' }],
    },
    {
        post_id: 15632,
        creator_id: 4,
        creator: 'Russell Robinson',
        creator_image: 'perry.png',
        registerDate: null,
        image: 'slider-default.png',
        text: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' }, { user_id: 2, comment: 'Sed iaculis urna id elit tincidunt placerat.' }, { user_id: 3, comment: 'Quisque venenatis ante ut erat accumsan mollis.' }, { user_id: 4, comment: 'dddddd' }, { user_id: 5, comment: 'Vivamus a nibh ut mauris imperdiet sagittis.' }],
    },
    {
        post_id: 13342,
        creator_id: 2,
        creator: 'Laura Harper',
        creator_image: 'max.png',
        registerDate: '10/03/2022',
        image: null,
        text: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'Praesent pulvinar ex ac volutpat faucibus.' }, { user_id: 2, comment: 'Vivamus vel diam in nulla consectetur vestibulum.' }, { user_id: 3, comment: 'Sed iaculis urna id elit tincidunt placerat.' }, { user_id: 4, comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' }, { user_id: 5, comment: 'Praesent pulvinar ex ac volutpat faucibus.' }],
    },
    {
        post_id: 10932,
        creator_id: 10,
        creator: 'Roger Alvarez',
        creator_image: 'mike.png',
        registerDate: '10/03/2022',
        image: 'slider-default.png',
        text: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }, { user_id: 4 }, { user_id: 5 }, { user_id: 6 }, { user_id: 7 }],
        comments: [{ user_id: 1, comment: 'Quisque venenatis ante ut erat accumsan mollis.' }, { user_id: 2, comment: 'Vivamus a nibh ut mauris imperdiet sagittis.' }, { user_id: 3, comment: 'Ut id odio quis dui semper varius.' }, { user_id: 4, comment: 'In sit amet urna pellentesque sapien vulputate sodales.' }, { user_id: 5, comment: 'Etiam tincidunt nibh ac mollis malesuada.' }],
    },
    {
        post_id: 13434,
        creator_id: 5,
        creator: 'Laura Sara',
        creator_image: 'ben.png',
        registerDate: '10/03/2022',
        image: null,
        text: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'Ut consectetur tortor vitae pellentesque aliquam.' }, { user_id: 2, comment: 'In sodales mi fermentum aliquam egestas.' }, { user_id: 3, comment: 'Quisque venenatis ante ut erat accumsan mollis.' }, { user_id: 4, comment: 'Etiam tincidunt nibh ac mollis malesuada.' }, { user_id: 5, comment: 'Etiam gravida leo ut diam pellentesque venenatis.' }],
    },
    {
        post_id: 13887,
        creator_id: 1,
        creator: 'Gary Ortiz',
        creator_image: 'adam.jpg',
        registerDate: '10/03/2022',
        image: 'slider-default.png',
        text: '',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'Quisque venenatis ante ut erat accumsan mollis.' }, { user_id: 2, comment: 'Phasellus venenatis justo vel elementum sagittis.' }, { user_id: 3, comment: 'Sed iaculis urna id elit tincidunt placerat.' }, { user_id: 4, comment: 'Etiam gravida leo ut diam pellentesque venenatis.' }, { user_id: 5, comment: 'Vivamus vel diam in nulla consectetur vestibulum.' }],
    }];

export const RECIPES = [
    {
        user_id: 1,
        creator: 'FGV',
        creator_image: null,
        registerDate: '10/04/2022',
        images: ['recipe01.jpg', 'recipe01.jpg', 'recipe01.jpg'],
        title: 'Panqueca de Avocado',
        instructions: `
        - Preparação do Avocado: Corte o avocado ao meio, retire o caroço e, com uma colher, retire a polpa. Amasse a polpa do avocado com um garfo até formar um purê liso.<br>
        - Mistura dos Ingredientes Secos: Em uma tigela grande, misture a farinha, o açúcar, o fermento em pó, o bicarbonato de sódio e o sal.<br>
        - Mistura dos Ingredientes Molhados: Em outra tigela, bata o ovo. Adicione o leite, o óleo (ou manteiga derretida), o purê de avocado e o extrato de baunilha. Misture bem até que todos os ingredientes estejam incorporados.<br>
        - Combinação dos Ingredientes: Despeje a mistura dos ingredientes molhados sobre os ingredientes secos. Mexa delicadamente até que a massa esteja homogênea, mas não misture demais. A massa deve ter alguns grumos.<br>
        - Cozimento das Panquecas: Aqueça uma frigideira grande ou uma chapa em fogo médio. Unte levemente com manteiga ou óleo. Despeje cerca de 1/4 de xícara de massa na frigideira para cada panqueca. Cozinhe até que bolhas comecem a se formar na superfície da panqueca e as bordas pareçam firmes, cerca de 2-3 minutos. Vire a panqueca e cozinhe por mais 1-2 minutos até que esteja dourada dos dois lados. Transfira as panquecas prontas para um prato e mantenha-as aquecidas enquanto cozinha o restante da massa.<br>
        - Servir: Sirva as panquecas de avocado quentes, acompanhadas de mel, xarope de bordo, frutas frescas ou iogurte, conforme desejado.<br>`,
        ingredients: ['1 avocado maduro (ou abacate pequeno)', '1 xícara de farinha de trigo (ou farinha de trigo integral para uma versão mais saudável)', '1 colher de sopa de açúcar (pode ser substituído por mel ou adoçante a gosto)', '1 colher de chá de fermento em pó', '1/2 colher de chá de bicarbonato de sódio', '1/4 colher de chá de sal', '1 ovo grande', '1 xícara de leite (pode usar leite vegetal como amêndoa, soja ou aveia)', '1 colher de sopa de óleo vegetal (ou manteiga derretida)', '1 colher de chá de extrato de baunilha', 'Manteiga ou óleo para cozinhar as panquecas'],
        cookTime: '30 min',
        servings: 4,
        calories: 300,
        liked: false,
        favorited: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }],
    },
    {
        user_id: 2,
        creator: 'Irani',
        creator_image: '',
        registerDate: '12/04/2022',
        images: ['recipe02.jpg'],
        title: 'Yakisoba Vegetariano',
        instructions: `
        - Cozimento do Macarrão: Em uma panela grande com água fervente e salgada, cozinhe o macarrão para yakisoba conforme as instruções da embalagem, até que esteja al dente. Reserve 1 xícara da água do cozimento, depois escorra o macarrão.
        - Preparação dos Legumes: Enquanto o macarrão cozinha, aqueça um pouco de óleo em uma frigideira grande ou wok em fogo médio-alto. Adicione a cenoura, os pimentões, o brócolis, a couve-flor, a cebola e o alho-poró. Refogue por cerca de 5 minutos até que os legumes estejam macios, mas ainda crocantes.
        - Molho e Finalização: Em uma tigela pequena, misture o molho de soja, o molho de ostra vegetariano, o saquê mirin, o amido de milho e o azeite de gergelim. Despeje o molho sobre os legumes na frigideira e mexa bem para cobrir. Adicione o alho picado e continue cozinhando por mais 1-2 minutos.
        - Mistura com Macarrão: Adicione o macarrão cozido à frigideira com os legumes e o molho. Mexa delicadamente para combinar todos os ingredientes e aquecer o macarrão. Se o molho parecer muito grosso, adicione um pouco da água do cozimento reservada até atingir a consistência desejada.
        - Servir: Divida o yakisoba vegetariano em pratos individuais e sirva imediatamente. Você pode polvilhar com cebolinha picada ou sementes de gergelim torradas para decorar, se desejar.`,
        ingredients: [
            "300g de macarrão para yakisoba", "1 unidade grande de cenoura",
            "1 unidade de pimentão vermelho", "1 unidade de pimentão amarelo",
            "1 maço de brócolis", "1/2 cabeça de couve-flor",
            "1 unidade grande de cebola", "1 unidade média de alho-poró",
            "1/4 xícara de molho de soja", "2 colheres de sopa de molho de ostra vegetariano",
            "2 colheres de sopa de saquê mirin", "1 colher de sopa de amido de milho",
            "1 colher de chá de azeite de gergelim", "2 dentes de alho picado"
        ],
        cookTime: '25 min',
        servings: 6,
        calories: 350,
        liked: false,
        favorited: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }, { user_id: 4, comment: 'dddddd' }, { user_id: 5, comment: 'eeeee' }],
    },
    {
        user_id: 3,
        creator: 'Tomasetto',
        creator_image: null,
        registerDate: '23/05/2022',
        images: ['recipe03.jpg'],
        title: 'Farofa Verão',
        instructions: `
    - Preparo dos Ingredientes: Aqueça uma frigideira grande em fogo médio. Adicione o azeite e refogue a cebola e o alho até ficarem macios e perfumados, cerca de 3 minutos.
    - Adição dos Legumes: Acrescente a cenoura, o pimentão, o milho, a ervilha e os pimentões à frigideira. Cozinhe por mais 5 minutos, mexendo ocasionalmente, até que os legumes estejam macios.
    - Farofa: Adicione a farinha de mandioca à frigideira e mexa bem para incorporar todos os ingredientes. Cozinhe por mais 3-5 minutos, mexendo sempre, até que a farofa esteja dourada e crocante.
    - Finalização e Servir: Tempere a farofa com sal e pimenta a gosto. Transfira para uma travessa de servir e polvilhe com salsinha picada antes de servir.`,
        ingredients: [
            "2 xícaras de farinha de mandioca",
            "1 colher de sopa de azeite de oliva",
            "1 cebola média picada",
            "2 dentes de alho picados",
            "1 cenoura ralada",
            "1/2 pimentão vermelho picado",
            "1/2 pimentão amarelo picado",
            "1/2 xícara de milho verde",
            "1/2 xícara de ervilha",
        ],
        cookTime: '20 min',
        servings: 6,
        calories: 250,
        liked: false,
        favorited: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }],
    },
    {
        user_id: 4,
        creator: 'Russell Robinson',
        creator_image: 'perry.png',
        registerDate: '28/05/2022',
        images: ['recipe04.jpg'],
        title: 'Patê de Rúcula',
        instructions: 'Add the cooked spaghetti to the skillet with the pancetta and garlic. Toss to combine. Remove the skillet from heat and quickly stir in the egg and cheese mixture, using tongs to evenly coat the spaghetti. If the sauce seems too thick, add reserved pasta water, a little at a time, until desired consistency is reached. Season with freshly ground black pepper and salt to taste. Garnish with chopped fresh parsley before serving. Enjoy your delicious Spaghetti Carbonara!',
        ingredients: [
            "2 xícaras de folhas de rúcula",
            "1 xícara de castanha de caju crua",
            "1/4 de xícara de azeite de oliva",
            "Suco de 1 limão",
            "2 dentes de alho",
            "Sal e pimenta-do-reino a gosto"
        ],
        cookTime: '30 min',
        servings: 4,
        calories: 300,
        liked: false,
        favorited: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }],
    }];

export const EVENTS = [
    {
        creator: 'FGV',
        creator_image: '',
        registerDate: '09/10/2022',
        image: 'event01.jpg',
        title: 'Vegan Festival',
        local: 'Local X, Rua Y',
        startingDate: '10/10/2022',
        endingDate: '12/10/2022',
        startingHour: '10:00',
        endingHour: '18:00',
        description: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        confirmed: [{ id: '432193921' }, { id: '981793921' }, { id: '54793921' }, { id: '981274611' }, { id: '11059673' }, { id: '03374655' }, { id: '02756208' }, { id: '672943900' }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }],
    },
    {
        creator: 'Irani',
        creator_image: null,
        registerDate: '05/04/2022',
        image: 'event02.jpg',
        title: 'Vegan Fest',
        local: 'Street X, Avenue Test',
        startingDate: '11/10/2022',
        endingDate: null,
        startingHour: '10:00',
        endingHour: '18:00',
        description: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        confirmed: [{ id: '032193921' }, { id: '432193921' }, { id: '54793921' }, { id: '981274611' }, { id: '11059673' }, { id: '02756208' }, { id: '672943900' }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }],
    },
    {
        creator: 'Tomasetto',
        creator_image: null,
        registerDate: '10/03/2022',
        image: 'event03.jpg',
        title: 'Vegan Street Market',
        local: 'Local X, Rua Y',
        startingDate: '17/10/2022',
        endingDate: null,
        startingHour: '12:00',
        endingHour: '18:00',
        description: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        confirmed: [{ id: '032193921' }, { id: '432193921' }, { id: '981793921' }, { id: '54793921' }, { id: '981274611' }, { id: '11059673' }, { id: '03374655' }, { id: '02756208' }, { id: '672943900' }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }],
    },
    {
        creator: 'Vokin',
        creator_image: null,
        registerDate: '10/03/2022',
        image: 'event04.jpg',
        title: 'Vegan Mystic Fest',
        local: 'Local X, Rua Y',
        startingDate: '18/10/2022',
        endingDate: null,
        startingHour: '12:00',
        endingHour: '18:00',
        description: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        confirmed: [{ id: '032193921' }, { id: '432193921' }, { id: '981793921' }, { id: '54793921' }, { id: '551793900' }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }],
    }];

//verificar se não é melhor deixar posts e receitas em uma biblioteca separada
export const USER = {
    id: 4,
    name: 'Russell Robinson',
    username: 'russell.robinson',
    description: 'i am a programmer',
    birth: '19/07/2000',
    email: 'teste@gmail.com',
    identify: 'vegan',
    country: 'Brasil',
    city: 'São Paulo',
    background: '',
    image: 'perry.png',
    interests: [
        {
            icon: 'wine',
            color: 'secondary',
            description: 'Nightlife',
        },
        {
            icon: 'restaurant',
            color: 'tertiary',
            description: 'Dining',
        },
        {
            icon: 'videocam',
            color: 'dark',
            description: 'Movies',
        }],
    posts: [{
        post_id: 13412,
        creator: 'Russell Robinson',
        creator_image: 'perry.png',
        registerDate: '10/03/2022',
        image: 'slider-default.png',
        text: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }, { user_id: 4 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }, { user_id: 4, comment: 'dddddd' }, { user_id: 5, comment: 'eeeee' }],
    },
    {
        post_id: 13832,
        creator: 'Russell Robinson',
        creator_image: 'perry.png',
        registerDate: null,
        image: null,
        text: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }, { user_id: 4, comment: 'dddddd' }, { user_id: 5, comment: 'eeeee' }],
    },
    {
        post_id: 13992,
        creator: 'Russell Robinson',
        creator_image: 'perry.png',
        registerDate: '10/03/2022',
        image: 'slider-default.png',
        text: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }, { user_id: 4 }, { user_id: 5 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }, { user_id: 4, comment: 'dddddd' }, { user_id: 5, comment: 'eeeee' }],
    }],
    recipes: [{
        user_id: 1,
        creator: 'FGV',
        creator_image: null,
        registerDate: null,
        image: 'recipe01.jpg',
        title: 'Panqueca de Avocado',
        text: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }],
    },
    {
        user_id: 2,
        creator: 'Russell Robinson',
        creator_image: 'perry.png',
        registerDate: '10/03/2022',
        image: 'recipe02.jpg',
        title: 'Yakisoba Vegetariano',
        text: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }, { user_id: 4, comment: 'dddddd' }, { user_id: 5, comment: 'eeeee' }],
    },
    {
        user_id: 3,
        creator: 'Russell Robinson',
        creator_image: 'perry.png',
        registerDate: '10/03/2022',
        image: 'recipe03.jpg',
        title: 'Farofa Verão',
        text: 'wait a minute. wait a minute, doc. are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.',
        liked: false,
        likes: [{ user_id: 1 }, { user_id: 2 }, { user_id: 3 }],
        comments: [{ user_id: 1, comment: 'aaaaaa' }, { user_id: 2, comment: 'bbbbbbb' }, { user_id: 3, comment: 'ccccc' }],
    }]
}

export const USERS = [
    { id: 1, name: "Gary Ortiz", username: 'gary.ortiz', identify: "vegan", image: "adam.jpg", email: "gortiz0@mapy.cz", country: "Indonesia", modified: "2015-05-16", birth_date: "1997-05-16" },
    { id: 2, name: "Albert Williamson", username: 'albert03', identify: "interested", image: "", email: "awilliamson1@narod.ru", country: "China", modified: "2015-03-11", birth_date: "1997-03-11" },
    { id: 3, name: "Mildred Maria Fuller", username: 'fuller02', identify: "vegan", image: "", email: "mfuller2@npr.org", country: "Peru", modified: "2015-02-15", birth_date: "1997-02-15" },
    { id: 4, name: "Russell Robinson", username: 'russell.robinson', identify: "vegetarian", image: "perry.png", email: "rrobinson3@google.pl", country: "Belarus", modified: "2014-10-31", birth_date: "1997-10-31" },
    { id: 5, name: "Laura Sara Harper", username: 'laura.harper', identify: "vegan", image: "ben.png", email: "lharper4@boston.com", country: "Philippines", modified: "2015-01-14", birth_date: "1997-01-14" },
    { id: 6, name: "Larry Sanders", username: 'larry.sdr', identify: "vegan", image: "max.png", email: "lsanders5@cornell.edu", country: "China", modified: "2015-01-11", birth_date: "1997-01-11" },
    { id: 7, name: "Michael Rice", username: 'm.rice', identify: "vegan", image: "", email: "mrice6@geocities.jp", country: "Philippines", modified: "2014-12-06", birth_date: "1997-12-06" },
    { id: 8, name: "Sara Harris", username: 'sara_harris', identify: "vegetarian", image: "", email: "sharris7@deliciousdays.com", country: "Indonesia", modified: "2014-11-05", birth_date: "1997-11-05" },
    { id: 9, name: "Phyllis Webb", username: 'phyllis002', identify: "vegetarian", image: "", email: "pwebb8@reddit.com", country: "China", modified: "2015-04-02", birth_date: "1997-04-02" },
    { id: 10, name: "Roger Alvarez", username: 'roger.alv', identify: "vegan", image: "mike.png", email: "ralvarez9@nsw.gov.au", country: "Finland", modified: "2015-03-21", birth_date: "1997-03-21" },
    { id: 11, name: "Maria Carpenter", username: 'maria.carpenter', identify: "interested", image: "", email: "mcarpentera@so-net.ne.jp", country: "Sweden", modified: "2015-08-18", birth_date: "1997-08-18" },
];

export const RECENT_SEARCH = [
    { "id": 5, name: "Laura Harper", username: 'laura.harper', identify: "vegan", image: "ben.png", email: "lharper4@boston.com", country: "Philippines", modified: "2015-01-14", birth_date: "1997-01-14" },
    { "id": 6, name: "Larry Sanders", username: 'larry.sdr', identify: "vegan", image: "max.png", email: "lsanders5@cornell.edu", country: "China", modified: "2015-01-11", birth_date: "1997-01-11" },
    { "id": 11, name: "Maria Carpenter", username: 'maria.carpenter', identify: "interested", image: "", email: "mcarpentera@so-net.ne.jp", country: "Sweden", modified: "2015-08-18", birth_date: "1997-08-18" },
]